### PR TITLE
chore: update org name

### PR DESCRIPTION
**Pull request by Readpato**
As title says, update org name wherever possible

### CODE REVIEW

**Comment by TheJoin95** [comment]
What are all these white spaces fix?

**Comment by Readpato** [comment]
Good question, I think its the formatter from the IDE that's applying the changes, which I have set up to format on save.

I can revert as it seems it has done that automatically, let me know!

The deleting of white spaces is interesting though haha

**Comment by TheJoin95** [comment]
Please revert them. Yeah, maybe it's needed but I won't risk anything with a risk free PR for updating links

**Comment by Readpato** [comment]
Sounds good, no problem :)

**Comment by Readpato** [comment]
@TheJoin95 Removed all white spaces, the issue that was happening was that the editor had a rule set to `true` by default which was 
```
`"remove_trailing_whitespace_on_save": Whether or not to remove any trailing whitespace from lines of a buffer before saving it.
```

That was causing the issue. PR should be good to go. Let me know!

**Review by TheJoin95 — APPROVED** [review]
ty

**Pull request merged**
